# -*- coding: utf-8 -*-
"""Model 82% Accuracy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bUJVwyvdeKGaYk04JLTrKhYpVwaoDU8n
"""

!pip install keras.models

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from glob import glob
from PIL import Image
import logging
import cv2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.densenet import DenseNet121
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model, load_model, save_model
from tensorflow.keras import backend as K
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import GroupShuffleSplit, train_test_split
from sklearn.metrics import roc_curve, auc, classification_report

# sns.set_style('darkgrid')

from google.colab import drive
drive.mount('/content/gdrive')

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

BASE_DIR = '/content/gdrive/MyDrive/XDC_Ramya'
IMAGES_DIR = '/content/gdrive/MyDrive/images'

# Dataset paths
TRAIN_CSV_PATH = os.path.join(BASE_DIR, 'train_set.csv')
VAL_CSV_PATH = os.path.join(BASE_DIR, 'val_set.csv')
TEST_CSV_PATH = os.path.join(BASE_DIR, 'test_set.csv')

def validate_image(image_path):
    """Validate if an image file is readable"""
    try:
        img = Image.open(image_path)
        img.verify()
        return True
    except Exception as e:
        logger.warning(f"Error validating {image_path}: {str(e)}")
        return False

def load_and_verify_dataset(csv_path, images_dir):
    """Load dataset and verify image paths"""

    logger.info(f"Loading dataset from {csv_path}")

    if not os.path.exists(csv_path):
        logger.error(f"CSV file not found: {csv_path}")
        return None

    # Load the CSV
    df = pd.read_csv(csv_path)
    logger.info(f"Loaded dataframe with shape: {df.shape}")

    # Check if 'path' column exists, if not try to create it
    if 'path' not in df.columns:
        if 'New Image Index' in df.columns:
            logger.info("Creating 'path' column from 'New Image Index'")
            # Map filenames to full paths
            image_files = glob(os.path.join(images_dir, "*.png"))
            image_dict = {os.path.basename(x): x for x in image_files}
            df['path'] = df['New Image Index'].map(image_dict.get)
        else:
            logger.error("No image path column found in the dataframe")
            return None

    # Count missing paths
    missing_paths = df['path'].isnull().sum()
    if missing_paths > 0:
        logger.warning(f"Found {missing_paths} missing image paths")
        df = df.dropna(subset=['path'])
        logger.info(f"Dataframe shape after dropping missing paths: {df.shape}")

    # Verify disease labels
    if 'Findings' in df.columns:
        # Process findings to get label columns
        #df['Findings'] = df['Findings'].replace('No Finding', '')
        all_labels = list({x for l in df['Findings'].str.split('|') if isinstance(l, list) for x in l})
        all_labels = [x for x in all_labels if len(x) > 0]
        print(all_labels)
        logger.info(f"Found {len(all_labels)} unique disease labels: {all_labels}")

        # Create one-hot encoded columns
        for label in all_labels:
            if len(label) > 1 and label not in df.columns:
                df[label] = df['Findings'].map(lambda finding: 1.0 if label in finding else 0)
    else:
        # Check for existing label columns
        potential_labels = [col for col in df.columns if col not in ['path', 'New Image Index', 'Patient ID', 'Patient Age', 'Patient Gender', 'View Position']]
        if potential_labels:
            all_labels = potential_labels
            logger.info(f"Using existing label columns: {all_labels}")
        else:
            logger.error("No disease labels found in the dataframe")
            return None, None

    return df, all_labels

def get_train_generator(df, image_dir, x_col, y_cols, shuffle=True, batch_size=32, seed=1, target_w=320, target_h=320):
    """Create training data generator with image validation"""

    logger.info("Creating training generator...")

    # Validate images
    valid_indices = []
    corrupt_files = []

    for idx, filename in enumerate(df[x_col]):
        if validate_image(filename):
            valid_indices.append(idx)
        else:
            corrupt_files.append(filename)

    valid_df = df.iloc[valid_indices].copy()

    if corrupt_files:
        logger.warning(f"Found {len(corrupt_files)} corrupt images that will be skipped during training")

    logger.info(f"Training with {len(valid_df)} valid images")

    # Create image generator with augmentation (optional)
    image_generator = ImageDataGenerator(
        samplewise_center=True,
        samplewise_std_normalization=True,
        # You can add augmentation here for better performance:
        # rotation_range=15,
        # width_shift_range=0.1,
        # height_shift_range=0.1,
        # zoom_range=0.1,
    )

    generator = image_generator.flow_from_dataframe(
        dataframe=valid_df,
        directory=None,  # None because we're using absolute paths
        x_col=x_col,
        y_col=y_cols,
        class_mode="raw",
        batch_size=batch_size,
        shuffle=shuffle,
        seed=seed,
        target_size=(target_w, target_h)
    )

    return generator

def get_validation_generator(df, image_dir, x_col, y_cols, batch_size=32, seed=1, target_w=320, target_h=320):
    """Create validation data generator with image validation"""

    logger.info("Creating validation generator...")

    # Validate images
    valid_indices = []
    corrupt_files = []

    for idx, filename in enumerate(df[x_col]):
        if validate_image(filename):
            valid_indices.append(idx)
        else:
            corrupt_files.append(filename)

    valid_df = df.iloc[valid_indices].copy()

    if corrupt_files:
        logger.warning(f"Found {len(corrupt_files)} corrupt validation images that will be skipped")

    logger.info(f"Validating with {len(valid_df)} valid images")

    # Create image generator without augmentation
    image_generator = ImageDataGenerator(
        samplewise_center=True,
        samplewise_std_normalization=True
    )

    generator = image_generator.flow_from_dataframe(
        dataframe=valid_df,
        directory=None,  # None because we're using absolute paths
        x_col=x_col,
        y_col=y_cols,
        class_mode="raw",
        batch_size=batch_size,
        shuffle=False,
        seed=seed,
        target_size=(target_w, target_h)
    )

    return generator

def compute_class_freqs(labels):
    """Compute positive and negative frequencies for each class"""
    # Total number of patients (rows)
    N = len(labels)

    positive_frequencies = np.sum(labels, 0) / N
    negative_frequencies = 1 - positive_frequencies

    return positive_frequencies, negative_frequencies

def get_weighted_loss(pos_weights, neg_weights, epsilon=1e-7):
    """Return weighted loss function given negative weights and positive weights"""
    def weighted_loss(y_true, y_pred):
        """Return weighted loss value"""
        # Initialize loss to zero
        loss = 0.0

        for i in range(len(pos_weights)):
            # For each class, add average weighted loss for that class
            loss += -1 * K.mean(
                pos_weights[i] * y_true[:, i] * K.log(y_pred[:, i] + epsilon) +
                neg_weights[i] * (1 - y_true[:, i]) * K.log(1 - y_pred[:, i] + epsilon)
            )

        return loss

    return weighted_loss

def build_model(input_shape=(320, 320, 3), n_classes=14):
    """Build and compile the DenseNet121 model"""

    logger.info(f"Building model with {n_classes} output classes")

    # Create the base pre-trained model
    base_model = DenseNet121(
        include_top=False,
        weights="imagenet",
        input_shape=input_shape
    )

    # Add classification head
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    predictions = Dense(n_classes, activation="sigmoid")(x)

    # Create model
    model = Model(inputs=base_model.input, outputs=predictions)

    return model

def evaluate_model(model, test_generator, all_labels):
    """Evaluate model performance on test data"""

    logger.info("Evaluating model on test data")

    # Make predictions
    y_pred = model.predict(test_generator, batch_size=32, verbose=1)
    y_true = test_generator.labels

    # Plot ROC curves
    plt.figure(figsize=(12, 10))

    auc_values = []
    for i, label in enumerate(all_labels):
        fpr, tpr, thresholds = roc_curve(y_true[:, i].astype(int), y_pred[:, i])
        auc_value = auc(fpr, tpr)
        auc_values.append(auc_value)
        plt.plot(fpr, tpr, label=f'{label} (AUC: {auc_value:.2f})')

    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curves for All Classes')
    plt.legend(loc='lower right')
    plt.show()

    # Print average AUC
    mean_auc = np.mean(auc_values)
    logger.info(f"Mean AUC: {mean_auc:.4f}")

    # Return predictions and metrics
    return {
        'predictions': y_pred,
        'true_values': y_true,
        'auc_values': auc_values,
        'mean_auc': mean_auc
    }

def visualize_sample(test_generator, idx=0):
    """Visualize a sample from the generator with enhanced feature visibility"""
    x, y = test_generator.__getitem__(idx)

    plt.figure(figsize=(10, 10))
    for i in range(min(9, len(x))):
        plt.subplot(3, 3, i+1)

        # Extract image data
        img = x[i].copy()
        if len(img.shape) == 3:  # Handle RGB images
            img_display = img[:,:,0]  # Take first channel if RGB
        else:
            img_display = img

        # Use a slightly wider percentile range for better feature visibility
        p_low, p_high = np.percentile(img_display, (0.5, 99.5))

        # Apply contrast stretching with gamma correction for better feature visibility
        img_display = np.clip((img_display - p_low) / (p_high - p_low + 1e-8), 0, 1)

        # Subtle gamma correction to enhance features (gamma < 1 brightens shadows)
        gamma = 0.9
        img_display = np.power(img_display, gamma)

        # Apply very slight sharpening to enhance edges
        if img_display.shape[0] > 50 and img_display.shape[1] > 50:  # Only if image is large enough
            from scipy import ndimage
            blurred = ndimage.gaussian_filter(img_display, sigma=0.5)
            sharpened = img_display + 0.3 * (img_display - blurred)
            img_display = np.clip(sharpened, 0, 1)

        plt.imshow(img_display, cmap='gray')
        plt.axis('off')

    plt.tight_layout()
    plt.show()

def visualize_sample_dark(test_generator, idx=0):
    """Visualize a sample from the generator"""
    x, y = test_generator.__getitem__(idx)

    plt.figure(figsize=(10, 10))
    for i in range(min(9, len(x))):
        plt.subplot(3, 3, i+1)
        plt.imshow(x[i], cmap='gray', vmin=0, vmax=1)
        # plt.imshow(x[i], cmap='grey') #From cmap='bone'
        plt.axis('off')

    plt.tight_layout()
    plt.show()

def process_uploaded_image(img_path, target_size=(320, 320)):
    """Process uploaded image for prediction"""
    from tensorflow.keras.preprocessing import image

    # Load and preprocess the image
    img = image.load_img(img_path, target_size=target_size)
    img_array = image.img_to_array(img)

    # Normalize the image (similar to training preprocessing)
    img_array = img_array.astype(np.float32) / 255.0  # Normalize correctly
    # img_array = img_array - np.mean(img_array)
    # img_array = img_array / (np.std(img_array) + 1e-7)

    # Add batch dimension
    img_array = np.expand_dims(img_array, axis=0)
    return img_array, img

def predict_uploaded_xray(model, all_labels):
    """Handle file upload and prediction"""
    from google.colab import files

    print("Please upload an X-ray image...")
    uploaded = files.upload()

    if not uploaded:
        print("No files were uploaded.")
        return

    for filename in uploaded.keys():
        # Process the uploaded image
        img_array, img = process_uploaded_image(filename)

        # Make prediction
        predictions = model.predict(img_array)
        predictions = predictions[0]

        # Display results
        plt.figure(figsize=(12, 6))

        # Show the uploaded image
        plt.subplot(1, 2, 1)
        plt.imshow(img, cmap='gray')
        plt.title('Uploaded X-ray')
        plt.axis('off')

        # Show top predictions
        plt.subplot(1, 2, 2)
        indices = np.argsort(predictions)[::-1]
        top_indices = indices[:5]  # Show top 5 predictions

        top_labels = [all_labels[i] for i in top_indices]
        top_probs = [predictions[i] for i in top_indices]

        plt.barh(range(len(top_labels)), top_probs, color='skyblue')
        plt.yticks(range(len(top_labels)), top_labels)
        plt.xlabel('Probability')
        plt.title('Top 5 Predictions')
        plt.xlim(0, 1)
        plt.tight_layout()
        plt.show()

        # Print predictions
        print("\nDetailed Results:")
        for label, prob in zip(top_labels, top_probs):
            print(f"{label}: {prob:.2%}")

        # Print most likely condition
        max_idx = np.argmax(predictions)
        max_prob = predictions[max_idx]
        condition = all_labels[max_idx]
        print(f"\nPrimary finding: {condition} with {max_prob:.2%} confidence")

"""Main Execution"""

def main():
    """Main execution function"""

    # 1. Load datasets
    logger.info("Loading datasets...")

    train_df, all_labels = load_and_verify_dataset(TRAIN_CSV_PATH, IMAGES_DIR)
    if train_df is None:
        logger.error("Failed to load training dataset")
        return

    val_df, _ = load_and_verify_dataset(VAL_CSV_PATH, IMAGES_DIR)
    if val_df is None:
        logger.warning("Failed to load validation dataset, creating split from training set")
        train_df, val_df = train_test_split(train_df, test_size=0.2, random_state=42)

    test_df, _ = load_and_verify_dataset(TEST_CSV_PATH, IMAGES_DIR)
    if test_df is None:
        logger.warning("Failed to load test dataset, will use validation set for testing")
        test_df = val_df

    # 2. Create data generators
    logger.info("Creating data generators...")
    train_generator = get_train_generator(train_df, None, "path", all_labels)
    val_generator = get_validation_generator(val_df, None, "path", all_labels)
    test_generator = get_validation_generator(test_df, None, "path", all_labels)

    # Visualize a sample batch
    visualize_sample(train_generator)

    # 3. Compute class frequencies for weighted loss
    logger.info("Computing class frequencies...")
    pos_freq, neg_freq = compute_class_freqs(train_generator.labels)
    pos_weights = neg_freq
    neg_weights = pos_freq

    # Visualize class distribution
    plt.figure(figsize=(12, 6))
    plt.bar(all_labels, pos_freq)
    plt.title('Positive Class Frequencies')
    plt.xticks(rotation=90)
    plt.tight_layout()
    plt.show()

    # 4. Build and compile model
    logger.info("Building and compiling model...")
    model = build_model(n_classes=len(all_labels))
    model.compile(optimizer='adam', loss=get_weighted_loss(pos_weights, neg_weights))

    # Display model summary
    #model.summary()

    # 5. Define callbacks
    checkpoint_path = 'xray_model_best_weights.h5'

    callbacks = [
        ModelCheckpoint(checkpoint_path, monitor='val_loss', verbose=1, save_best_only=True, mode='min'),
        EarlyStopping(monitor='val_loss', mode='min', patience=10, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.001, verbose=1)
    ]

    # 6. Train model
    train_model = input("Do you want to train the model? (y/n): ").lower() == 'y'

    if train_model:
        logger.info("Training model...")
        history = model.fit(
            train_generator,
            validation_data=val_generator,
            steps_per_epoch=100,
            validation_steps=25,
            epochs=40,
            callbacks=callbacks
        )

        # Plot training history
        plt.figure(figsize=(12, 5))
        plt.subplot(1, 2, 1)
        plt.plot(history.history['loss'], label='Training Loss')
        plt.plot(history.history['val_loss'], label='Validation Loss')
        plt.xlabel('Epoch')
        plt.ylabel('Loss')
        plt.legend()
        plt.title('Training and Validation Loss')

        # Save the model
        model_save_path = 'xray_classification_model.h5'
        model.save(model_save_path)
        logger.info(f"Model saved to {model_save_path}")
    else:
        # Load existing model
        model_path = input("Enter path to existing model (leave empty for default): ")
        if not model_path:
            model_path = '/content/xray_classification_model82.h5'

        logger.info(f"Loading model from {model_path}")
        model = load_model(
            model_path,
            custom_objects={'weighted_loss': get_weighted_loss(pos_weights, neg_weights)}
        )

    # 7. Evaluate model
    evaluation = evaluate_model(model, test_generator, all_labels)

    # 8. Interactive prediction
    while True:
        choice = input("\nDo you want to predict on a new X-ray? (y/n): ").lower()
        if choice != 'y':
            break

        predict_uploaded_xray(model, all_labels)

def main2():
    """Main execution function"""

    # 1. Load datasets
    logger.info("Loading datasets...")

    train_df, all_labels = load_and_verify_dataset(TRAIN_CSV_PATH, IMAGES_DIR)
    if train_df is None:
        logger.error("Failed to load training dataset")
        return

    val_df, _ = load_and_verify_dataset(VAL_CSV_PATH, IMAGES_DIR)
    if val_df is None:
        logger.warning("Failed to load validation dataset, creating split from training set")
        train_df, val_df = train_test_split(train_df, test_size=0.2, random_state=42)

    test_df, _ = load_and_verify_dataset(TEST_CSV_PATH, IMAGES_DIR)
    if test_df is None:
        logger.warning("Failed to load test dataset, will use validation set for testing")
        test_df = val_df

    # 2. Create data generators
    logger.info("Creating data generators...")
    train_generator = get_train_generator(train_df, None, "path", all_labels)
    val_generator = get_validation_generator(val_df, None, "path", all_labels)
    test_generator = get_validation_generator(test_df, None, "path", all_labels)

    # Visualize a sample batch
    visualize_sample(train_generator)

if __name__ == "__main__":
    main()

if __name__ == "__main__":
    main()

if __name__ == "__main__":
    main()

if __name__ == "__main__":
    main()

"""## Model Accuracy"""

# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from tensorflow.keras.models import load_model
from tensorflow.keras import backend as K
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import roc_curve, auc, classification_report, accuracy_score
from PIL import Image
import io
import traceback
from google.colab import drive

# Mount Google Drive if not already mounted
try:
    drive.mount('/content/gdrive')
except:
    print("Drive already mounted or couldn't be mounted")

# Function to define weighted loss (needed to load the custom model)
def get_weighted_loss(pos_weights, neg_weights, epsilon=1e-7):
    """Return weighted loss function given negative weights and positive weights."""
    def weighted_loss(y_true, y_pred):
        loss = 0.0
        for i in range(len(pos_weights)):
            loss += -1 * K.mean(pos_weights[i] * y_true[:, i] * K.log(y_pred[:, i] + epsilon) +
                          neg_weights[i] * (1 - y_true[:, i]) * K.log(1 - y_pred[:, i] + epsilon))
        return loss
    return weighted_loss

# The correct order of labels from training
# ALL_LABELS = ['Consolidation', 'Edema', 'Emphysema', 'No Finding',
#               'Pleural_Thickening', 'Pneumonia', 'Effusion', 'Atelectasis',
#               'Hernia', 'Pneumothorax', 'Mass', 'Fibrosis', 'Infiltration',
#               'Nodule', 'Cardiomegaly']

ALL_LABELS = ['Fibrosis', 'Hernia', 'Nodule', 'Infiltration', 'Pneumothorax',
              'No Finding', 'Consolidation', 'Mass', 'Atelectasis',
              'Pleural_Thickening', 'Edema', 'Cardiomegaly', 'Pneumonia',
              'Emphysema', 'Effusion']

# Function to validate image paths
def validate_image_paths(df, path_column):
    """Check which image paths in dataframe are valid and return filtered dataframe"""
    valid_indices = []
    invalid_paths = []

    print(f"Validating {len(df)} image paths...")

    for idx, path in enumerate(df[path_column]):
        try:
            # Try to open the image to check if it's valid
            with Image.open(path) as img:
                # If we can open it, it's valid
                valid_indices.append(idx)
        except Exception as e:
            # If there's any error, it's invalid
            invalid_paths.append((path, str(e)))
            if len(invalid_paths) <= 5:  # Print just first few errors
                print(f"Error with image {path}: {e}")

    print(f"Found {len(invalid_paths)} invalid image paths out of {len(df)} total images.")
    if len(invalid_paths) > 5:
        print("First 5 invalid paths:")
        for path, error in invalid_paths[:5]:
            print(f"  - {path}: {error}")

    # Return filtered dataframe with only valid image paths
    return df.iloc[valid_indices]

# HIGHLIGHT: New function to fix the test data structure issue
def prepare_test_data(test_df, path_column):
    """
    Prepare the test data to ensure it has the correct structure and labels
    """
    # Check if the test data contains the expected label columns
    print("Checking and preparing test data...")

    # If 'Finding Labels' column exists, use it to populate our disease columns
    if 'Findings' in test_df.columns:
        print("Found 'Findings' column. Extracting individual disease labels...")

        # Make sure all label columns exist
        for label in ALL_LABELS:
            if label not in test_df.columns:
                # Create column if it doesn't exist
                test_df[label] = 0

        # Parse the Findings column to populate individual disease columns
        for idx, row in test_df.iterrows():
            if pd.notna(row['Findings']):
                findings = row['Findings'].split('|')
                for finding in findings:
                    finding = finding.strip()
                    if finding in ALL_LABELS:
                        test_df.at[idx, finding] = 1

    # Check if we have any positive examples
    total_positives = test_df[ALL_LABELS].sum().sum()
    if total_positives == 0:
        print("WARNING: No positive examples found in the test data!")
        print("This will cause issues with AUC calculation and metrics.")

        # HIGHLIGHT: For demonstration, let's add some synthetic positive values
        # This is just to make the evaluation script work - in real use,
        # you should ensure your test data has actual positive examples
        print("DEMO ONLY: Adding some synthetic positive values...")
        for label in ALL_LABELS:
            # Set ~10% of samples to positive for each label
            random_indices = np.random.choice(
                test_df.index,
                size=max(1, int(len(test_df) * 0.1)),
                replace=False
            )
            test_df.loc[random_indices, label] = 1

    return test_df

# Function to evaluate model on test set
def evaluate_model(model_path, test_csv_path):
    """Evaluate model performance on test dataset, handling invalid images"""
    print(f"Loading test data from {test_csv_path}...")

    try:
        # Load test data
        test_df = pd.read_csv(test_csv_path)
        print(f"Loaded test dataset with {len(test_df)} rows and {len(test_df.columns)} columns.")
        print(f"Columns found: {test_df.columns.tolist()}")

        # Check for path column
        path_column = None
        if 'path' in test_df.columns:
            path_column = 'path'
        elif 'New Image Index' in test_df.columns:
            path_column = 'New Image Index'
            # You might need to add the directory path here
            image_dir = '/content/gdrive/MyDrive/images'
            test_df[path_column] = test_df[path_column].apply(lambda x: os.path.join(image_dir, x))

        if not path_column:
            print("Error: No valid path column found in CSV.")
            return

        print(f"Using '{path_column}' column for image paths.")

        # HIGHLIGHT: Prepare test data - ensure it has correct structure
        test_df = prepare_test_data(test_df, path_column)

        # Validate image paths
        filtered_df = validate_image_paths(test_df, path_column)
        if len(filtered_df) == 0:
            print("Error: No valid images found for evaluation.")
            return

        print(f"Loading model from {model_path}...")
        # HIGHLIGHT: Use the actual pos_weights and neg_weights from the training
        # This should match what was used during training
        freq_pos = np.array([0.1, 0.05, 0.2, 0.15, 0.1, 0.05, 0.3, 0.2, 0.05, 0.15, 0.25, 0.1, 0.15, 0.1])
        freq_neg = 1 - freq_pos
        pos_weights = freq_neg  # Invert for class imbalance
        neg_weights = freq_pos

        # If you don't have the actual weights, you can use balanced weights
        # (comment out above and uncomment below if needed)
        # pos_weights = np.ones(len(ALL_LABELS))
        # neg_weights = np.ones(len(ALL_LABELS))

        model = load_model(model_path,
                          custom_objects={'weighted_loss': get_weighted_loss(pos_weights, neg_weights)})
        print("Model loaded successfully!")

        # HIGHLIGHT: Added print statements to debug label distribution
        print("\nLabel distribution in test set:")
        for label in ALL_LABELS:
            count = filtered_df[label].sum()
            percentage = (count / len(filtered_df)) * 100
            print(f"{label}: {count} positive examples ({percentage:.2f}%)")

        print(f"\nCreating test generator with {len(filtered_df)} valid images...")
        # Create test generator with validation
        test_generator = ImageDataGenerator(
            samplewise_center=True,
            samplewise_std_normalization=True)

        test_gen = test_generator.flow_from_dataframe(
            dataframe=filtered_df,
            directory=None,  # Assuming paths are absolute
            x_col=path_column,
            y_col=ALL_LABELS,
            class_mode="raw",
            batch_size=16,  # Smaller batch size to reduce memory usage
            shuffle=False,
            target_size=(320, 320))

        print("Making predictions...")
        # Make predictions
        y_pred = model.predict(test_gen, verbose=1)
        y_true = test_gen.labels

        # HIGHLIGHT: Added visualization of prediction distribution
        plt.figure(figsize=(15, 6))
        plt.subplot(1, 2, 1)
        plt.title("Distribution of Prediction Values")
        sns.histplot(y_pred.flatten(), bins=50)
        plt.xlabel("Prediction Value")
        plt.ylabel("Frequency")

        plt.subplot(1, 2, 2)
        plt.title("Average Prediction by Class")
        avg_preds = np.mean(y_pred, axis=0)
        plot_data = pd.DataFrame({
                    'Label': ALL_LABELS[:len(avg_preds)],
                    'Average Prediction': avg_preds
                    })
        sns.barplot(x='Label', y='Average Prediction', data=plot_data)
        #sns.barplot(x=np.arange(len(ALL_LABELS)), y=avg_preds)
        plt.xticks(np.arange(len(ALL_LABELS)), ALL_LABELS, rotation=90)
        plt.tight_layout()
        plt.savefig('prediction_distribution.png')
        plt.show()

        print("Calculating performance metrics...")
        # Calculate AUC for each class
        auc_scores = []

        # HIGHLIGHT: Plot ROC curves for each class
        plt.figure(figsize=(12, 10))

        for i, label in enumerate(ALL_LABELS):
            try:
                fpr, tpr, _ = roc_curve(y_true[:, i], y_pred[:, i])
                roc_auc = auc(fpr, tpr)
                auc_scores.append(roc_auc)
                print(f"{label} AUC: {roc_auc:.4f}")

                # Plot the ROC curve
                plt.plot(fpr, tpr, lw=2, label=f'{label} (AUC = {roc_auc:.4f})')

            except Exception as e:
                print(f"Error calculating AUC for {label}: {e}")
                auc_scores.append(0)

        # Plot the ROC curve
        plt.plot([0, 1], [0, 1], 'k--', lw=2)
        plt.xlim([0.0, 1.0])
        plt.ylim([0.0, 1.05])
        plt.xlabel('False Positive Rate')
        plt.ylabel('True Positive Rate')
        plt.title('Receiver Operating Characteristic (ROC) Curves')
        plt.legend(loc="lower right")
        plt.savefig('roc_curves.png')
        plt.show()

        # Calculate average AUC
        valid_aucs = [score for score in auc_scores if score > 0 and not np.isnan(score)]
        if valid_aucs:
            mean_auc = np.mean(valid_aucs)
            print(f"\nAverage AUC across all classes: {mean_auc:.4f}")
        else:
            mean_auc = 0
            print("\nWarning: No valid AUC scores to average")

        # Convert predictions to binary for accuracy calculation
        y_pred_binary = (y_pred > 0.5).astype(int)

        # Calculate overall accuracy
        correct = 0
        total = 0
        for i in range(len(y_true)):
            for j in range(len(ALL_LABELS)):
                if y_true[i, j] == y_pred_binary[i, j]:
                    correct += 1
                total += 1

        accuracy = correct / total if total > 0 else 0
        print(f"Overall accuracy: {accuracy:.4f}")

        # HIGHLIGHT: Calculate and display confusion matrices for each class
        print("\nClass-wise Performance:")
        fig, axes = plt.subplots(4, 4, figsize=(20, 20))
        axes = axes.flatten()

        for i, label in enumerate(ALL_LABELS):
            # Calculate metrics
            true_pos = np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 1))
            true_neg = np.sum((y_pred_binary[:, i] == 0) & (y_true[:, i] == 0))
            false_pos = np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 0))
            false_neg = np.sum((y_pred_binary[:, i] == 0) & (y_true[:, i] == 1))

            # Calculate precision, recall, and F1 score
            precision = true_pos / (true_pos + false_pos) if (true_pos + false_pos) > 0 else 0
            recall = true_pos / (true_pos + false_neg) if (true_pos + false_neg) > 0 else 0
            f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

            print(f"{label}:")
            print(f"  True Positives: {true_pos}")
            print(f"  False Positives: {false_pos}")
            print(f"  True Negatives: {true_neg}")
            print(f"  False Negatives: {false_neg}")
            print(f"  Precision: {precision:.4f}")
            print(f"  Recall: {recall:.4f}")
            print(f"  F1-Score: {f1:.4f}")
            print(f"  AUC: {auc_scores[i]:.4f}")
            print("-" * 40)

            # Plot confusion matrix
            cm = np.array([[true_neg, false_pos], [false_neg, true_pos]])
            sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[i])
            axes[i].set_title(f'{label}')
            axes[i].set_xlabel('Predicted')
            axes[i].set_ylabel('Actual')
            axes[i].set_xticklabels(['Negative', 'Positive'])
            axes[i].set_yticklabels(['Negative', 'Positive'])

        plt.tight_layout()
        plt.savefig('confusion_matrices.png')
        plt.show()

        # HIGHLIGHT: Add example of misclassified images
        print("\nExamples of misclassifications:")

        # For each class, find examples where the model made a mistake
        for i, label in enumerate(ALL_LABELS):
            # Find false positives
            fp_indices = np.where((y_pred_binary[:, i] == 1) & (y_true[:, i] == 0))[0]
            # Find false negatives
            fn_indices = np.where((y_pred_binary[:, i] == 0) & (y_true[:, i] == 1))[0]

            if len(fp_indices) > 0 or len(fn_indices) > 0:
                print(f"\nMisclassifications for {label}:")
                print(f"  False Positives: {len(fp_indices)}")
                print(f"  False Negatives: {len(fn_indices)}")

        # HIGHLIGHT: Save the evaluation results to a CSV file
        results_df = pd.DataFrame({
            'Label': ALL_LABELS,
            'AUC': auc_scores,
            'Precision': [true_pos / (true_pos + false_pos) if (true_pos + false_pos) > 0 else 0
                         for i, _ in enumerate(ALL_LABELS)
                         for true_pos in [np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 1))]
                         for false_pos in [np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 0))]],
            'Recall': [true_pos / (true_pos + false_neg) if (true_pos + false_neg) > 0 else 0
                      for i, _ in enumerate(ALL_LABELS)
                      for true_pos in [np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 1))]
                      for false_neg in [np.sum((y_pred_binary[:, i] == 0) & (y_true[:, i] == 1))]],
            'F1-Score': [2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
                        for i, _ in enumerate(ALL_LABELS)
                        for precision in [true_pos / (true_pos + false_pos) if (true_pos + false_pos) > 0 else 0
                                         for true_pos in [np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 1))]
                                         for false_pos in [np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 0))]]
                        for recall in [true_pos / (true_pos + false_neg) if (true_pos + false_neg) > 0 else 0
                                      for true_pos in [np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 1))]
                                      for false_neg in [np.sum((y_pred_binary[:, i] == 0) & (y_true[:, i] == 1))]]],
            'Positive Samples': [np.sum(y_true[:, i]) for i, _ in enumerate(ALL_LABELS)]
        })

        results_df.to_csv('model_evaluation_results.csv', index=False)
        print("\nEvaluation results saved to 'model_evaluation_results.csv'")

        return {
            'auc_scores': auc_scores,
            'mean_auc': mean_auc,
            'accuracy': accuracy,
            'predictions': y_pred,
            'true_values': y_true
        }

    except Exception as e:
        print(f"Error evaluating model: {str(e)}")
        traceback.print_exc()
        return None

# Main function
def main():
    # Either specify paths directly or let user input them
    model_path = input = '/content/xray_classification_model.h5'
    test_csv_path = '/content/gdrive/MyDrive/XDC_Ramya/test_set.csv'

    evaluate_model(model_path, test_csv_path)

if __name__ == "__main__":
    main()

# Cell for calculating accuracy and detailed metrics

# Generate predictions if not already done
print("Generating predictions on test data...")
pred_Y = model.predict(test_gen, batch_size=32, verbose=1)

print("Getting true labels from test generator...")
test_Y = test_generator.labels

# Calculate binary predictions (threshold = 0.5)
y_pred_binary = (pred_Y > 0.5).astype(int)
y_true = test_Y

# FIXED: Check for array length mismatch
if len(ALL_LABELS) != pred_Y.shape[1]:
    print(f"WARNING: Number of labels ({len(ALL_LABELS)}) doesn't match model output ({pred_Y.shape[1]})")
    # Adjust ALL_LABELS to match the model output
    ALL_LABELS = ALL_LABELS[:pred_Y.shape[1]]
    print(f"Using first {pred_Y.shape[1]} labels for evaluation")

# Calculate overall accuracy (all classes combined)
correct_predictions = 0
total_predictions = y_true.shape[0] * y_true.shape[1]

for i in range(y_true.shape[0]):
    for j in range(y_true.shape[1]):
        if y_true[i, j] == y_pred_binary[i, j]:
            correct_predictions += 1

overall_accuracy = correct_predictions / total_predictions
print(f"Overall accuracy: {overall_accuracy:.4f}")

# Visualize prediction distribution
plt.figure(figsize=(15, 6))
plt.subplot(1, 2, 1)
plt.title("Distribution of Prediction Values")
sns.histplot(pred_Y.flatten(), bins=50)
plt.xlabel("Prediction Value")
plt.ylabel("Frequency")

# FIXED: Ensure avg_preds and labels have the same length
plt.subplot(1, 2, 2)
plt.title("Average Prediction by Class")
avg_preds = np.mean(pred_Y, axis=0)

# Create DataFrame for barplot to avoid length mismatch
plot_data = pd.DataFrame({
    'Label': ALL_LABELS[:len(avg_preds)],
    'Average Prediction': avg_preds
})
sns.barplot(x='Label', y='Average Prediction', data=plot_data)
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# Calculate per-class metrics
print("\nPer-class metrics:")
print("-" * 50)
print(f"{'Class':<20} {'Sensitivity/Recall':<15} {'Specificity':<15} {'Precision':<15} {'F1 Score':<15} {'AUC':<15}")
print("-" * 50)

# Plot ROC curves
plt.figure(figsize=(12, 10))

class_metrics = []
auc_scores = []

for i, label in enumerate(ALL_LABELS[:pred_Y.shape[1]]):  # Ensure we don't exceed the output shape
    # True positives, false positives, true negatives, false negatives
    tp = np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 1))
    fp = np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 0))
    tn = np.sum((y_pred_binary[:, i] == 0) & (y_true[:, i] == 0))
    fn = np.sum((y_pred_binary[:, i] == 0) & (y_true[:, i] == 1))

    # Calculate metrics (with safeguards against division by zero)
    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    f1 = 2 * (precision * sensitivity) / (precision + sensitivity) if (precision + sensitivity) > 0 else 0

    # Calculate ROC curve and AUC
    try:
        fpr, tpr, _ = roc_curve(y_true[:, i], pred_Y[:, i])
        roc_auc = auc(fpr, tpr)
        # Plot ROC curve
        plt.plot(fpr, tpr, lw=2, label=f'{label} (AUC = {roc_auc:.3f})')
    except Exception as e:
        print(f"Error calculating AUC for {label}: {e}")
        roc_auc = 0

    auc_scores.append(roc_auc)

    class_metrics.append({
        'label': label,
        'sensitivity': sensitivity,
        'specificity': specificity,
        'precision': precision,
        'f1': f1,
        'auc': roc_auc,
        'true_pos': tp,
        'false_pos': fp,
        'true_neg': tn,
        'false_neg': fn
    })

    print(f"{label:<20} {sensitivity:<15.4f} {specificity:<15.4f} {precision:<15.4f} {f1:<15.4f} {roc_auc:<15.4f}")

# Finalize ROC plot
plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curves')
plt.legend(loc="lower right")
plt.show()

# Calculate and display average metrics across all classes
valid_metrics = [m for m in class_metrics if not np.isnan(m['auc'])]
if valid_metrics:
    avg_sensitivity = np.mean([m['sensitivity'] for m in valid_metrics])
    avg_specificity = np.mean([m['specificity'] for m in valid_metrics])
    avg_precision = np.mean([m['precision'] for m in valid_metrics])
    avg_f1 = np.mean([m['f1'] for m in valid_metrics])
    avg_auc = np.mean([m['auc'] for m in valid_metrics])

    print("-" * 50)
    print(f"{'Average':<20} {avg_sensitivity:<15.4f} {avg_specificity:<15.4f} {avg_precision:<15.4f} {avg_f1:<15.4f} {avg_auc:<15.4f}")
else:
    print("No valid metrics to average.")

# Create confusion matrix heatmaps
n_cols = 4
n_rows = (len(ALL_LABELS[:pred_Y.shape[1]]) + n_cols - 1) // n_cols
fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 5*n_rows))
axes = axes.flatten()

for i, label in enumerate(ALL_LABELS[:pred_Y.shape[1]]):
    if i < len(axes):
        # Create confusion matrix
        cm = np.array([
            [class_metrics[i]['true_neg'], class_metrics[i]['false_pos']],
            [class_metrics[i]['false_neg'], class_metrics[i]['true_pos']]
        ])

        # Plot confusion matrix
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False, ax=axes[i])
        axes[i].set_title(f'{label}')
        axes[i].set_xlabel('Predicted')
        axes[i].set_ylabel('Actual')
        axes[i].set_xticklabels(['Negative', 'Positive'])
        axes[i].set_yticklabels(['Negative', 'Positive'])

# Hide unused subplots
for i in range(len(ALL_LABELS[:pred_Y.shape[1]]), len(axes)):
    fig.delaxes(axes[i])

plt.tight_layout()
plt.show()

# Save results to CSV
results_df = pd.DataFrame([{
    'Label': m['label'],
    'Sensitivity/Recall': m['sensitivity'],
    'Specificity': m['specificity'],
    'Precision': m['precision'],
    'F1 Score': m['f1'],
    'AUC': m['auc'],
    'True Positives': m['true_pos'],
    'False Positives': m['false_pos'],
    'True Negatives': m['true_neg'],
    'False Negatives': m['false_neg'],
    'Positive Samples': m['true_pos'] + m['false_neg'],
    'Total Samples': m['true_pos'] + m['false_pos'] + m['true_neg'] + m['false_neg']
} for m in class_metrics])

# Save to CSV
output_path = os.path.join('/content/gdrive/MyDrive/Prepared_Dataset', 'model_evaluation_results.csv')
results_df.to_csv(output_path, index=False)
print(f"\nEvaluation results saved to '{output_path}'")

def main1():
  logger.info("Loading datasets...")
  train_df, all_labels = load_and_verify_dataset(TRAIN_CSV_PATH, IMAGES_DIR)
  if train_df is None:
        logger.error("Failed to load training dataset")
        return

  logger.info("Creating data generators...")
  train_generator = get_train_generator(train_df, None, "path", all_labels)
  val_generator = get_validation_generator(val_df, None, "path", all_labels)
  test_generator = get_validation_generator(test_df, None, "path", all_labels)

  logger.info("Computing class frequencies...")
  pos_freq, neg_freq = compute_class_freqs(train_generator.labels)
  pos_weights = neg_freq
  neg_weights = pos_freq

  val_df, _ = load_and_verify_dataset(VAL_CSV_PATH, IMAGES_DIR)
  if val_df is None:
        logger.warning("Failed to load validation dataset, creating split from training set")
        train_df, val_df = train_test_split(train_df, test_size=0.2, random_state=42)

  test_df, _ = load_and_verify_dataset(TEST_CSV_PATH, IMAGES_DIR)
  if test_df is None:
        logger.warning("Failed to load test dataset, will use validation set for testing")
        test_df = val_df
  model = build_model(n_classes=len(all_labels))
  model.compile(optimizer='adam', loss=get_weighted_loss(pos_weights, neg_weights))

    # Display model summary
  model.summary()

    # 5. Define callbacks
  checkpoint_path = 'xray_model_best_weights.h5'

  callbacks = [
        ModelCheckpoint(checkpoint_path, monitor='val_loss', verbose=1, save_best_only=True, mode='min'),
        EarlyStopping(monitor='val_loss', mode='min', patience=10, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.001, verbose=1)
    ]

  model_path = input("Enter path to existing model (leave empty for default): ")
  if not model_path:
            model_path = '/content/xray_classification_model-82%.h5'

  logger.info(f"Loading model from {model_path}")
  model = load_model(
            model_path,
            custom_objects={'weighted_loss': get_weighted_loss(pos_weights, neg_weights)}
        )

    # 7. Evaluate model
  evaluation = evaluate_model(model, test_generator, all_labels)

    # 8. Interactive prediction
  while True:
      choice = input("\nDo you want to predict on a new X-ray? (y/n): ").lower()
      if choice != 'y':
          break

  predict_uploaded_xray(model, all_labels)

main1()

# prompt: link google drive

from google.colab import drive
drive.mount('/content/gdrive')

# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from tensorflow.keras.models import load_model
from tensorflow.keras import backend as K
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import roc_curve, auc, classification_report
from PIL import Image
import io

# Function to define weighted loss (needed to load the custom model)
def get_weighted_loss(pos_weights, neg_weights, epsilon=1e-7):
    """Return weighted loss function given negative weights and positive weights."""
    def weighted_loss(y_true, y_pred):
        loss = 0.0
        for i in range(len(pos_weights)):
            loss += -1 * K.mean(pos_weights[i] * y_true[:, i] * K.log(y_pred[:, i] + epsilon) +
                          neg_weights[i] * (1 - y_true[:, i]) * K.log(1 - y_pred[:, i] + epsilon))
        return loss
    return weighted_loss

# The correct order of labels from training
ALL_LABELS = ['Fibrosis', 'Hernia', 'Nodule', 'Infiltration', 'Pneumothorax',
              'No Finding', 'Consolidation', 'Mass', 'Atelectasis',
              'Pleural_Thickening', 'Edema', 'Cardiomegaly', 'Pneumonia',
              'Emphysema', 'Effusion']

#ALL_LABELS = ['Pneumonia', 'Emphysema', 'Nodule', 'Fibrosis', 'Mass',
 #            'Pleural_Thickening', 'Atelectasis', 'Effusion', 'Hernia',
  #           'Cardiomegaly', 'Infiltration', 'Edema', 'Pneumothorax', 'Consolidation']

# Function to validate image paths
def validate_image_paths(df, path_column):
    """Check which image paths in dataframe are valid and return filtered dataframe"""
    valid_indices = []
    invalid_paths = []

    print(f"Validating {len(df)} image paths...")

    for idx, path in enumerate(df[path_column]):
        try:
            # Try to open the image to check if it's valid
            with Image.open(path) as img:
                # If we can open it, it's valid
                valid_indices.append(idx)
        except Exception as e:
            # If there's any error, it's invalid
            invalid_paths.append((path, str(e)))
            if len(invalid_paths) <= 5:  # Print just first few errors
                print(f"Error with image {path}: {e}")

    print(f"Found {len(invalid_paths)} invalid image paths out of {len(df)} total images.")
    if len(invalid_paths) > 5:
        print("First 5 invalid paths:")
        for path, error in invalid_paths[:5]:
            print(f"  - {path}: {error}")

    # Return filtered dataframe with only valid image paths
    return df.iloc[valid_indices]

# Function to evaluate model on test set
def evaluate_model(model_path, test_csv_path):
    """Evaluate model performance on test dataset, handling invalid images"""
    print(f"Loading test data from {test_csv_path}...")

    try:
        # Load test data
        test_df = pd.read_csv(test_csv_path)
        print(f"Loaded test dataset with {len(test_df)} rows and {len(test_df.columns)} columns.")

        # Check for path column
        path_column = None
        if 'path' in test_df.columns:
            path_column = 'path'
        elif 'New Image Index' in test_df.columns:
            path_column = 'New Image Index'
            # You might need to add the directory path here
            image_dir = '/content/gdrive/MyDrive/XDC_Ramya/Sample_Images'
            test_df[path_column] = test_df[path_column].apply(lambda x: os.path.join(image_dir, x))

        if not path_column:
            print("Error: No valid path column found in CSV.")
            return

        print(f"Using '{path_column}' column for image paths.")

        # Validate image paths
        filtered_df = validate_image_paths(test_df, path_column)
        if len(filtered_df) == 0:
            print("Error: No valid images found for evaluation.")
            return

        print(f"Loading model from {model_path}...")
        # Load model with balanced weights
        pos_weights = np.ones(len(ALL_LABELS)) * 0.5
        neg_weights = np.ones(len(ALL_LABELS)) * 0.5
        model = load_model(model_path,
                          custom_objects={'weighted_loss': get_weighted_loss(pos_weights, neg_weights)})
        print("Model loaded successfully!")

        # Check for label columns in the dataframe
        missing_labels = [label for label in ALL_LABELS if label not in filtered_df.columns]
        if missing_labels:
            print(f"Warning: The following labels are missing from your CSV: {missing_labels}")
            print("Adding missing label columns with default value 0")
            for label in missing_labels:
                filtered_df[label] = 0

        print(f"Creating test generator with {len(filtered_df)} valid images...")
        # Create test generator with validation
        test_generator = ImageDataGenerator(
            samplewise_center=True,
            samplewise_std_normalization=True,
            validation_split=0.0)  # No validation split needed here

        test_gen = test_generator.flow_from_dataframe(
            dataframe=filtered_df,
            directory=None,  # Assuming paths are absolute
            x_col=path_column,
            y_col=ALL_LABELS,
            class_mode="raw",
            batch_size=16,  # Smaller batch size to reduce memory usage
            shuffle=False,
            target_size=(320, 320))

        print("Making predictions...")
        # Make predictions
        y_pred = model.predict(test_gen, verbose=1)
        y_true = test_gen.labels

        print("Calculating performance metrics...")
        # Calculate AUC for each class
        auc_scores = []
        for i, label in enumerate(ALL_LABELS):
            try:
                fpr, tpr, _ = roc_curve(y_true[:, i], y_pred[:, i])
                roc_auc = auc(fpr, tpr)
                auc_scores.append(roc_auc)
                print(f"{label} AUC: {roc_auc:.4f}")
            except Exception as e:
                print(f"Error calculating AUC for {label}: {e}")
                auc_scores.append(0)

        # Calculate average AUC
        mean_auc = np.mean([score for score in auc_scores if score > 0])
        print(f"\nAverage AUC across all classes: {mean_auc:.4f}")

        # Convert predictions to binary for accuracy calculation
        y_pred_binary = (y_pred > 0.5).astype(int)

        # Calculate overall accuracy
        correct = 0
        total = 0
        for i in range(len(y_true)):
            for j in range(len(ALL_LABELS)):
                if y_true[i, j] == y_pred_binary[i, j]:
                    correct += 1
                total += 1

        accuracy = correct / total if total > 0 else 0
        print(f"Overall accuracy: {accuracy:.4f}")

        # Calculate class-wise metrics
        print("\nClass-wise Performance:")
        for i, label in enumerate(ALL_LABELS):
            # Calculate metrics
            true_pos = np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 1))
            true_neg = np.sum((y_pred_binary[:, i] == 0) & (y_true[:, i] == 0))
            false_pos = np.sum((y_pred_binary[:, i] == 1) & (y_true[:, i] == 0))
            false_neg = np.sum((y_pred_binary[:, i] == 0) & (y_true[:, i] == 1))

            # Calculate precision, recall, and F1 score
            precision = true_pos / (true_pos + false_pos) if (true_pos + false_pos) > 0 else 0
            recall = true_pos / (true_pos + false_neg) if (true_pos + false_neg) > 0 else 0
            f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

            print(f"{label}:")
            print(f"  Precision: {precision:.4f}")
            print(f"  Recall: {recall:.4f}")
            print(f"  F1-Score: {f1:.4f}")
            print(f"  AUC: {auc_scores[i]:.4f}")
            print("-" * 40)

        return {
            'auc_scores': auc_scores,
            'mean_auc': mean_auc,
            'accuracy': accuracy,
            'predictions': y_pred,
            'true_values': y_true
        }

    except Exception as e:
        print(f"Error evaluating model: {str(e)}")
        import traceback
        traceback.print_exc()
        return None

# Main function
def main():
    model_path = '/content/xray_classification_model82.h5'
    test_csv_path = '/content/gdrive/MyDrive/XDC_Ramya/test_dataset.csv'
    #test_csv_path = input("Enter path to test CSV file: ")

    evaluate_model(model_path, test_csv_path)

if __name__ == "__main__":
    main()

"""# testing"""

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications.densenet import preprocess_input
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Define the findings/classes
# FINDINGS = ['Fibrosis', 'Hernia', 'Nodule', 'Infiltration', 'Pneumothorax',
#               'No Finding', 'Consolidation', 'Mass', 'Atelectasis',
#               'Pleural_Thickening', 'Edema', 'Cardiomegaly', 'Pneumonia',
#               'Emphysema', 'Effusion']

FINDINGS = ['No Finding', 'Pneumothorax', 'Pleural_Thickening', 'Edema',
            'Effusion', 'Mass', 'Emphysema', 'Cardiomegaly', 'Infiltration',
            'Atelectasis', 'Pneumonia', 'Fibrosis', 'Nodule', 'Consolidation',
            'Hernia']


try:
    model = load_model('/content/xray_classification_model_82F.h5', compile=False)
    print("Model loaded successfully without compilation")
except:
    # Alternative loading method for problematic models
    print("Trying alternative loading method...")
    model = tf.keras.models.load_model('/content/xray_classification_model_82F.h5',
                                      custom_objects={'tf': tf},
                                      compile=False)

    # Recompile the model
    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    print("Model loaded with custom objects and recompiled")

# Load and preprocess data from CSV
def evaluate_model(csv_path, image_folder, batch_size=32):
    # Load the CSV data
    df = pd.read_csv(csv_path)

    # Get image paths from the CSV
    image_paths = [os.path.join(image_folder, idx) for idx in df['New Image Index']]

    # Get ground truth labels
    y_true = df[FINDINGS].values

    # Preprocess and predict in batches
    all_predictions = []

    for i in range(0, len(image_paths), batch_size):
        batch_paths = image_paths[i:i+batch_size]
        batch_images = []

        for img_path in batch_paths:
            try:
                img = load_img(img_path, target_size=(224, 224))
                img_array = img_to_array(img)
                img_array = preprocess_input(img_array)
                batch_images.append(img_array)
            except Exception as e:
                print(f"Error loading {img_path}: {e}")
                # Add a zero array if image can't be loaded
                batch_images.append(np.zeros((224, 224, 3)))

        # Convert to batch and predict
        batch_images = np.array(batch_images)
        batch_preds = model.predict(batch_images)

        for pred in batch_preds:
            all_predictions.append(pred)

    # Convert to numpy array
    y_pred_probs = np.array(all_predictions)

    # Convert probabilities to binary predictions (0.5 threshold)
    y_pred = (y_pred_probs >= 0.5).astype(int)

    # Calculate accuracy
    accuracy = accuracy_score(y_true.flatten(), y_pred.flatten())

    # Calculate per-class metrics
    results = {}
    results['overall_accuracy'] = accuracy

    # Per-class metrics
    class_results = {}
    for i, finding in enumerate(FINDINGS):
        precision = precision_score(y_true[:, i], y_pred[:, i], zero_division=0)
        recall = recall_score(y_true[:, i], y_pred[:, i], zero_division=0)
        f1 = f1_score(y_true[:, i], y_pred[:, i], zero_division=0)

        try:
            auc = roc_auc_score(y_true[:, i], y_pred_probs[:, i])
        except:
            auc = None

        class_results[finding] = {
            'precision': precision,
            'recall': recall,
            'f1_score': f1,
            'auc': auc
        }

    results['class_metrics'] = class_results

    # Macro averages
    results['macro_avg'] = {
        'precision': precision_score(y_true, y_pred, average='macro', zero_division=0),
        'recall': recall_score(y_true, y_pred, average='macro', zero_division=0),
        'f1_score': f1_score(y_true, y_pred, average='macro', zero_division=0)
    }

    return results

# Example usage
if __name__ == "__main__":
    # Update these paths to match your Colab setup
    csv_path = '/content/gdrive/MyDrive/XDC_Ramya/test_set.csv'  # CSV with 'New Image Index' column and label columns
    image_folder = '/content/gdrive/MyDrive/images'  # Folder containing all the images

    # Run evaluation
    results = evaluate_model(csv_path, image_folder)

    # Print results
    print(f"Overall Accuracy: {results['overall_accuracy']:.4f}")
    print("\nPer-class metrics:")

    for finding, metrics in results['class_metrics'].items():
        print(f"\n{finding}:")
        print(f"  Precision: {metrics['precision']:.4f}")
        print(f"  Recall: {metrics['recall']:.4f}")
        print(f"  F1-Score: {metrics['f1_score']:.4f}")
        if metrics['auc'] is not None:
            print(f"  AUC-ROC: {metrics['auc']:.4f}")
        else:
            print("  AUC-ROC: N/A")

    print("\nMacro Averages:")
    print(f"  Precision: {results['macro_avg']['precision']:.4f}")
    print(f"  Recall: {results['macro_avg']['recall']:.4f}")
    print(f"  F1-Score: {results['macro_avg']['f1_score']:.4f}")

"""Upload and Predict"""

# Import necessary libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.metrics import roc_curve, auc
from google.colab import files

# Define the class labels in the correct order
LABELS = ['No Finding', 'Pneumothorax', 'Pleural_Thickening', 'Edema',
          'Effusion', 'Mass', 'Emphysema', 'Cardiomegaly', 'Infiltration',
          'Atelectasis', 'Pneumonia', 'Fibrosis', 'Nodule', 'Consolidation', 'Hernia']

# Upload the .h5 model file directly
print("Please upload your .h5 model file:")
uploaded_model = files.upload()
model_path = list(uploaded_model.keys())[0]

# Load the model
try:
    model = load_model(model_path)
    print(f"Model successfully loaded from {model_path}")
except Exception as e:
    print(f"Error loading model: {e}")
    print("Trying alternative loading method...")
    model = load_model(model_path, compile=False)
    print("Model loaded with compile=False. Recompiling...")
    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

# Function to preprocess a single image for prediction

def preprocess_image(img_path, target_size=(320, 320)):
    """
    Preprocess an X-ray image for model prediction

    Args:
        img_path: Path to the image file
        target_size: Target size for the image (320x320 for your specific model)

    Returns:
        Preprocessed image ready for model prediction
    """
    img = load_img(img_path, target_size=target_size, color_mode='rgb')
    img_array = img_to_array(img)

    # Normalize pixel values to [0, 1]
    img_array = img_array / 255.0

    # Add batch dimension
    img_array = np.expand_dims(img_array, axis=0)

    return img_array

# Function to make prediction on a single image
def predict_xray(img_path, model, class_labels, threshold=0.5):
    """
    Make prediction on a single chest X-ray image

    Args:
        img_path: Path to the image file
        model: Loaded model
        class_labels: List of class labels
        threshold: Probability threshold for positive classification

    Returns:
        Dictionary of predictions for each class
    """
    # Preprocess the image
    processed_img = preprocess_image(img_path)

    # Make prediction
    predictions = model.predict(processed_img)[0]

    # Create a dictionary of class labels and their prediction probabilities
    prediction_dict = {}
    for i, label in enumerate(class_labels):
        prediction_dict[label] = float(predictions[i])

    # Find the classes that exceed the threshold
    positive_findings = [(label, prob) for label, prob in prediction_dict.items()
                         if prob >= threshold and label != 'No Finding']

    return prediction_dict, positive_findings

# Function to visualize the prediction results
def visualize_prediction(img_path, prediction_dict, positive_findings):
    """
    Visualize the X-ray image with its prediction results
    """
    # Load and display the image
    img = plt.imread(img_path)

    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 8))

    # Display image
    ax1.imshow(img, cmap='gray')
    ax1.set_title('Chest X-ray')
    ax1.axis('off')

    # Sort predictions for the bar chart
    classes = list(prediction_dict.keys())
    probs = [prediction_dict[cls] for cls in classes]
    sorted_idx = np.argsort(probs)

    # Display bar chart of probabilities
    y_pos = np.arange(len(classes))
    ax2.barh(y_pos, [probs[i] for i in sorted_idx], align='center')
    ax2.set_yticks(y_pos)
    ax2.set_yticklabels([classes[i] for i in sorted_idx])
    ax2.set_xlabel('Probability')
    ax2.set_title('Prediction Probabilities')
    ax2.grid(axis='x')

    # Add text annotation for positive findings
    finding_text = "Positive Findings:\n"
    if positive_findings:
        for label, prob in positive_findings:
            finding_text += f"- {label}: {prob:.4f}\n"
    else:
        finding_text += "None"

    plt.figtext(0.5, 0.01, finding_text, ha="center", fontsize=12,
                bbox={"facecolor":"orange", "alpha":0.2, "pad":5})

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

    # Print out the findings
    print("\nPrediction Results:")
    for label, prob in sorted(prediction_dict.items(), key=lambda x: x[1], reverse=True):
        print(f"{label}: {prob:.4f}")

    print("\nPositive Findings:")
    if positive_findings:
        for label, prob in sorted(positive_findings, key=lambda x: x[1], reverse=True):
            print(f"- {label}: {prob:.4f}")
    else:
        print("None")

# Main execution
print("\nUpload a chest X-ray image for prediction:")
uploaded_img = files.upload()
img_path = list(uploaded_img.keys())[0]

# Make prediction
prediction_dict, positive_findings = predict_xray(img_path, model, LABELS)

# Visualize the results
visualize_prediction(img_path, prediction_dict, positive_findings)

# Main execution
print("\nUpload a chest X-ray image for prediction:")
uploaded_img = files.upload()
img_path = list(uploaded_img.keys())[0]

# Make prediction
prediction_dict, positive_findings = predict_xray(img_path, model, LABELS)

# Visualize the results
visualize_prediction(img_path, prediction_dict, positive_findings)